### ISSUE TITLE
bug: some elements report a 0x0 bounding box in playwright / inspector

### ISSUE THREAD

**Issue by mkilp** [emdgroup-liquid/liquid#1002]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://liquid.merck.design/liquid/guides/contributing/#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.12.5

### Framework bindings

React

### Current behavior

Using Playwrights react selectors I want to be able to click on the 0nth element inside a LdSelect. However due to some weirdness the LdOptions never report a valid bounding box even though the element is visible. Also does not report correctly in the React component tree:
![image](https://github.com/emdgroup-liquid/liquid/assets/8791079/6fc66fff-175f-4aad-8531-4000de7570c9)

### Expected behavior

Playwright can successfully identify the objects.

### Steps to reproduce

Run npm start
Run npx playwright test

### Code reproduction URL

https://github.com/mkilp/ld-modal-repro

### Additional information

Feel free to reach out if you want to discuss this!

**Comment by borisdiakur** [comment]
Hi @mkilp,

thanks for submitting this issue. I checked your repository and after adjusting a few things could run the test. Here is what I did:

__App.js:__
```diff
-import { useRef } from "react";
+import { useRef, useState } from "react";
import {
  LdButton,
  LdModal,
  LdTypo,
  LdSelect,
  LdOption
} from "@emdgroup-liquid/liquid/dist/react";
import "./styles.css";
import { defineCustomElements } from "@emdgroup-liquid/liquid/dist/loader";
import "@emdgroup-liquid/liquid/dist/css/liquid.global.css";

export default function App() {
  defineCustomElements();
  const modalRef = useRef(null);
  const tetherOptions = {
    bodyElement: modalRef.current,
    constraints: [{ to: "scrollParent" }]
  };
+ const [open, setOpen] = useState(false)
  return (
    <div className="App">
-     <LdModal ref={modalRef} tetherOptions={tetherOptions}>
+     <LdModal
+       ref={modalRef}
+       tetherOptions={tetherOptions}
+       open={open}
+       onLdmodalclosed={() => setOpen(false)}>
        <LdSelect
          filter
          placeholder={"select"}
          name={"filter"}
          mode="detached"
          tetherOptions={tetherOptions}
        >
          <LdOption key={0} value={"test"} selected={false} disabled={false}>
-           <LdTypo variant="h6">test</LdTypo>
+           test
          </LdOption>
        </LdSelect>
      </LdModal>

-     <LdButton onClick={() => modalRef.current.showModal()}>
+     <LdButton
+       onClick={() => {
+         setOpen(true)
+       }}>
        Open Modal
      </LdButton>
    </div>
  );
}
```

__example.spec.ts:__
```diff
import {expect, test} from "@playwright/test";

test('Custom Filter: Selected Filters Area', async ({page}) => {
  await page.goto('./');
- await page.locator('_react=LdButton').click();
- await page.locator('_react=LdSelect').click();
- let test = await page.locator('_react=LdSelect')
-     .locator("_react=LdOption")
-     .nth(0)
-     .click();
+
+ await page.getByRole('button', { name: 'Open Modal' }).click();
+
+ await page.getByLabel('select').click();
+ await page.getByRole('option', { name: 'test' }).click();
+
+ await page.getByLabel('test').click();
+ await page.getByRole('option', { name: 'test' }).click();
+
+ await page.getByLabel('Dismiss').click();
});
```

The `LdOption` component is not a UI-Component. It's only there for you to declaratively compose the options of the `LdSelect` component. So you cannot click it. What the `LdSelect` component does "under the hood" is the following: It watches the `LdOption`s and creates copies them to the popper element (that is handled by _Tether_) as `LdOptionInternal` components. The `LdOptionInternal` component is a UI component and can be clicked. Though, in your test code, it doesn't suffice to just change `LdOption` to `LdOptionInternal`, because the `LdOptionInternal` component is not located within the `LdSelect` component, but rather in the popper element.

To get around such issues when writing tests in general, I suggest you to use selectors which do not rely on implementation details. I also highly recommend you to have a look at Playwright's awesome [`codegen`](https://playwright.dev/docs/codegen) feature, which will help you to come up with correct selectors.
