### ISSUE TITLE
ld-sidenav: heading hidden and navitems positioned wrong on mobile

### ISSUE THREAD

**Issue by renet** [emdgroup-liquid/liquid#286]
**Bug description**

When a narrow collapsible `ld-sidenav` is collapsed and is being opened on mobile (viewport width < value of `breakpoint` prop), the following items are not styled correctly:

- `ld-sidenav-heading`s are hidden.
- `ld-sidenav-navitem`s are displayed in the wrong vertical position, whilst
- `ld-sidenav-separator`s inside the `ld-sidenav-slider` are positioned correctly.

**Steps to reproduce the behavior**

1. Go to https://codesandbox.io/s/liquid-sandbox-next-tailwind-z3wgi?file=/pages/index.tsx
2. Make sure the sidenav is collapsed.
3. Reduce the viewport to a width < value of `breakpoint` prop.
4. If necessary, click on the burger menu icon to open the `ld-sidenav`.

**Expected behavior**

- `ld-sidenav-heading`s are visible.
- `ld-sidenav-navitem`s are displayed in the right vertical position.

**Actual behavior**

- `ld-sidenav-heading`s are hidden.
- `ld-sidenav-navitem`s are displayed in the wrong vertical position

**Comment by borisdiakur** [comment]
Still broken 😬.  Reproduction instructions:

1. Navigate to https://emdgroup-liquid.github.io/liquid/components/ld-sidenav/#narrow-mode
2. Resize the view port to mobile
3. Click on Artificial Intelligence
4. Resize the view port to desktop

Current behavior:

<img width="493" alt="Screenshot 2022-05-04 at 11 18 41" src="https://user-images.githubusercontent.com/527049/166655521-e464742c-6fa6-4477-b90f-0fc2b1a7f8de.png">

Expected behavior:

<img width="479" alt="Screenshot 2022-05-04 at 16 36 47" src="https://user-images.githubusercontent.com/527049/166704922-b4364ed8-8c6a-4504-b030-f67ea379745e.png">
