### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by borisdiakur** [emdgroup-liquid/liquid#438]
A context menu (also called contextual menu or pop-up menu) is a menu that appears upon user interaction, such as a right-click or a long press (in touch screen environments). It offers a limited set of choices that are available in the current state, or context, of the application to which the menu belongs. Usually the available choices are actions related to the selected object.

Some screenshots for the usage of a context menu within a task management application (first is with mouse, second with touch screen):

<img width="504" alt="Screen Shot 2022-10-28 at 10 22 09" src="https://user-images.githubusercontent.com/527049/198540664-c0254a89-137e-4262-84c7-19de47e0d85c.png">
<img width="375" alt="Screen Shot 2022-10-28 at 10 22 58" src="https://user-images.githubusercontent.com/527049/198540668-3000b7ee-246f-4be2-832c-69c1de11feac.png">

**Comment by borisdiakur** [comment]
This repository is using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for features. This means:
- Feature requests are closed issues with `feature` label and `needed: votes` label.
- Bugs are open issues tagged with the bug label.

Upvote the description (top comment) of this issue with 👍 if you want it to be prioritized higher.

**Comment by zemirco** [comment]
I did some research and found some interesting concepts. They could serve as an inspiration.

**Palantir Blueprint**
https://blueprintjs.com/docs/#popover2-package/context-menu2
![image](https://user-images.githubusercontent.com/1132354/212332856-f3e395c2-cec8-4d54-a1a8-d1a13724081d.png)

**Elastic UI**
https://elastic.github.io/eui/#/navigation/context-menu
![image](https://user-images.githubusercontent.com/1132354/212333015-c20addb1-9565-48e7-a388-93d351b0a6f9.png)

**Microsoft Fluent UI**
https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu
![image](https://user-images.githubusercontent.com/1132354/212333183-7ea13e98-705b-450f-8962-5d214b9d356a.png)

**Twilio Paste**
https://paste.twilio.design/components/menu/
![image](https://user-images.githubusercontent.com/1132354/212333308-d25ccaf2-3ab3-4c00-8a67-6b3ca6331560.png)

Maybe that helps during the design and definition phase.

**Comment by renet** [comment]
Added a design for the context menu (needs review): https://www.figma.com/file/JcDMeUwec9e185HfBgT9XE/Liquid-Oxygen?node-id=11550%3A31414

We will probably implement a non-nested MVP of this component (no support for submenus) to reduce complexity and initial development time.

**Comment by zemirco** [comment]
Super nice :) I think it's a good idea to start simple and release a non-nested version first.

Sorry for hijacking this issues but I thought it fits well. You're currently using `tether` for positioning elements.

```json
  "dependencies": {
    "@stencil/core": "^3.0.0",
    "js-cookie": "^3.0.1",
    "tether": "^2.0.0"
  },
```

I believe tether is dead (although the README says something different) as there were no commits apart from bots since June 2022.

![image](https://user-images.githubusercontent.com/1132354/216559253-e63981bd-5dc4-4d7a-8dcc-89578c5f8d68.png)

The original maintainers stepped down 5 years ago

https://github.com/shipshapecode/tether/blame/0549620736a8d39c4899ab153eeac73e12eda487/README.md#L6-L15

Someone else tried to take over but nothing really happened so far

https://github.com/shipshapecode/tether/blame/master/README.md#L21

They recommend using Popper instead

https://popper.js.org/

Also Bootstrap had the same issue and they also moved away from tether to popper.

https://github.com/twbs/bootstrap/pull/22444

I'm super excited for getting the context menu! Thank you 👏 🥳

**Comment by borisdiakur** [comment]
@zemirco We have actually replaced popper with tether, because popper resulted in jerky positioning on iOS Safari during scrolling. We'll have an eye on this though. Maybe it even makes sense to use an [adapter pattern](https://refactoring.guru/design-patterns/adapter) here, just in case. What do you think @renet?
