### ISSUE TITLE
bug: setting a collapsed width on sidenav breaks alignment of navitems

### ISSUE THREAD

**Issue by mkilp** [emdgroup-liquid/liquid#509]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

4.4.4

### Framework bindings

React

### Current behavior

Forcing the sidenav to be collapsed and adding a NavItem with a custom image icon breaks the center alignment of the NavItem (including hover).

### Expected behavior

Icon to be correctly aligned within the NavBar (I assume centered?). Hover aligns correctly around size of object in icon slot.

### Steps to reproduce

https://codesandbox.io/s/sidenav-centering-bug-r3f9yt?file=/src/App.js

### Code reproduction URL

https://codesandbox.io/s/sidenav-centering-bug-r3f9yt?file=/src/App.js

**Comment by borisdiakur** [comment]
Hi @mkilp 👋

the `--ld-sidenav-width-collapsed` is actually a CSS variable that is meant for consumption and not manipulation. Meaning: If you have an element inside the sidenav, which "needs to **know**" how wide the sidenav is in narrow mode, it can use that variable. The sidenav component is already quite complex, and supporting all sorts of customizations using CSS custom props is quite challenging, because if we decide to do so, we have to cover all cases.

I'm curious though to what you are trying to achieve with this. If you have a custom design which other applications might also profit from, we might come up with a solution. A screenshot of your design would be helpful.

That said, if the only thing you want is to add more padding to the left and right, you can try to change the `--ld-sidenav-padding-x` variable (this will break accordions inside the sidenav however, if you have any).

**Comment by mkilp** [comment]
Hi @borisdiakur!
So sorry for the late reply. We are basically trying to achieve a "Quick Filter" image based sidebar.
I tried playing around with `--ld-sidenav-padding-x` and it def. does what I want it to. But to achieve what we are trying to accomplish I also introduced (or modified rather) `--ld-sidenav-navitem-icon-size` to get a nice big image button.

Example here: https://codesandbox.io/s/sidenav-centering-bug-r3f9yt?file=/src/App.js

This can probably be done way simpler with other components, let me know if you have an idea how to achieve what we are trying to do in a different way!

**Comment by mkilp** [comment]
Also i just discovered that the tooltip on hover is not aligning properly on our dev environment:
![image](https://user-images.githubusercontent.com/8791079/221912582-aa0510aa-7165-4b33-82a7-12cb0d121479.png)

Seems like it aligns automatically with:
`left: -75px !important` even though `left: 0px !important` would align it perfectly:
![image](https://user-images.githubusercontent.com/8791079/221912957-a1014933-76ea-4a3e-b248-8801c200a893.png)

How is the tooltip calculated?

**Comment by mkilp** [comment]
@borisdiakur do you have any idea about the tooltip issue?

**Comment by borisdiakur** [comment]
@mkilp I'm sorry, but I cannot reproduce your issue. I just tried it locally and it works on my end just by setting the `--ld-sidenav-navitem-icon-size` to some larger value. This also works for me when combining this with a custom `--ld-sidenav-padding-x`. Tooltip seems fine as well. Maybe you have some other setting that differs from what I'm testing. I'll try to figure out tomorrow. 🤞

Here is what I have:

https://user-images.githubusercontent.com/527049/223820090-a7eda55a-cf20-4b8f-9038-2e41fdb08b9b.mp4

**Comment by borisdiakur** [comment]
I actually just found out why it's not working in your sandbox: You are setting the `--ld-sidenav-navitem-icon-size` CSS custom prop on the `LdSidenavNavitem` component. What you should do is set it on the `LdSidenav` component, because it uses is for computation of other CSS values and passes it down to its sub components.

Here is how it looks for me in your sandbox after applying the above fix:

<img width="658" alt="Screenshot 2023-03-08 at 20 26 53" src="https://user-images.githubusercontent.com/527049/223823805-1e5bda93-6208-41ce-99e9-f1619d047800.png">
