### ISSUE TITLE
feat: Support for USA date format in date type Input ( MM / DD / YYYY )

### ISSUE THREAD

**Issue by Zorkann** [emdgroup-liquid/liquid#553]
### Prerequisites

- [X] I know [how to contribute a proper feature request](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#requesting-new-features).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing feature requests](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) that already request this feature, without success.

### Describe the feature request

Add a support for USA date format ( MM / DD / YYYY ) in Input date type component.

### Describe the use case

People in USA / Canada operates on a little different date type than Europe. It can be confusing for them so it's better to provide best UX we can. 

### Describe preferred solution

Would be really nice to have `dateFormat` property where we can define date format which we want to use. Example from: https://reactdatepicker.com/

![image](https://user-images.githubusercontent.com/28710560/222496973-f10fc741-c9dc-4f4e-9f62-6ccee3fc98f8.png)

### Describe alternatives

1. Property where we can pass localization. 
2. Input type date should react automatically based on the user browser selected localization.

### Additional information

If this is somehow already handled in the Input date type, just updating the docs is enough to close that issue :)

**Comment by borisdiakur** [comment]
Hello @Zorkann,

thank you for bringing up this topic. Your question about the date format has already come up in the past. Here is the thread for reference: https://github.com/emdgroup-liquid/liquid/discussions/279

It looks like we need to document our input component more thoroughly. Before doing that, I'd like to iterate here again on why there is no date format property on the input component:

I think we are aligned with all major browser vendors in our believe, that the display format of the date input element should respect the user's preferences and not ours. Specifically, we should not make a choice for all users as a whole, but allow each user to choose the date format that is most comprehensible and usable for her or him individually.

That said, I'd like to point out, that the input element already supports all sorts of date formats. If you don't see the date being displayed in the format, that you expect, it's most likely because the format is not configured accordingly in your system settings.

I'm attaching three screenshots which I just made on Windows  and Mac OS, illustrating how you, as a user, can configure your settings, so that the date is displayed in the desired format. The first two examples show the format, which you mentioned in your issue description (MM/DD/YYYY), being applied in the settings and picked up by the browser. The last screenshot shows my personal setting, where my primary language is English, but my preferred date format is dd.MM.YYYY and that both is respected by the input element. Please note, that if you change your settings (i.e. for testing purposes), you'll have to restart your browser for the changes to take effect.

<img width="1672" alt="Screenshot 2023-03-03 at 08 25 22" src="https://user-images.githubusercontent.com/527049/222671522-e98e239b-360d-4313-af69-4eac9ff1bc1c.png">

<img width="1548" alt="Screenshot 2023-03-03 at 8 31 36 AM" src="https://user-images.githubusercontent.com/527049/222671553-2e398da5-419e-41ef-b748-5c758164255f.png">

<img width="1548" alt="Screenshot 2023-03-03 at 09 25 25" src="https://user-images.githubusercontent.com/527049/222671570-05b74691-9fbc-4237-8d31-05705234cd88.png">

Another reason for why we stick to the native implementation of the date input, aside from [the ones mentioned in the linked discussion](https://github.com/emdgroup-liquid/liquid/discussions/279#discussioncomment-2280007), is that the date input element is a highly complex feature. In order to emphasize my point here, I'd like to comment on the library you mentioned in your issue description: It has, at the time of writing, [over 200 open issues](https://github.com/Hacker0x01/react-datepicker/issues). One issue, that is immediately apparent to me, is the following: If I click on the day within the input element itself, and then press the arrow up button, in order to increment the day, something unexpected happens: Instead of incrementing the day, the component sets the focus on the same day within the picker element. This is especially confusing for people with visual impairments. So, just because the component is used a lot, doesn't mean it is good. Moreover, the complexity of the component will be reflected in the bundle size.

Considering all of the above, I don't think that we will implement the feature that you are requesting. However, we definitely see the need for a more thorough documentation in regards to the input date format and on why things work the way they work.

Please feel free to comment, if you feel that there is anything we are missing our assertion.

**Comment by Zorkann** [comment]
Nope, everything good, thanks for quick response. So this issue can be closed after documentation is added i guess. 👍
