### ISSUE TITLE
bug: Tests fails after version > 4.6.0

### ISSUE THREAD

**Issue by Zorkann** [emdgroup-liquid/liquid#666]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

> 4.6.0

### Framework bindings

React

### Current behavior

We were using Liquid version 4.13.0 but we wanted to upgrade to newest version. We found out that 4.6.0 introduces some problems to our Jest + RTL tests. We are using CRA and we added the liquid component library into the `transformIgnorePatterns` to notify Jest that we want to compile Liquid library to CommonJS and so on.

### Expected behavior

Tests should be working as expected in versions above 4.5.0.

### Steps to reproduce

1. Use CRA
2. Add "node_modules/(?!@emdgroup-liquid)/" to transformIgnorePatterns for notify Jest that it should transform ESM modules
3. Use LdModal in component
4. Render the component with RTL

### Code reproduction URL

https://codesandbox.io/p/github/emdgroup-liquid/liquid-sandbox-cra-tailwind/csb-lqyi2w/draft/fervent-curran?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A52%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A52%2C%22startLineNumber%22%3A8%7D%5D

### Additional information

Additional case with modal component, tests are not failing but weird error message popped out: https://codesandbox.io/p/github/emdgroup-liquid/liquid-sandbox-cra-tailwind/csb-585zse/draft/great-meitner?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A5%7D%5D
We also tried to use experimental ESM support for Jest and it seems that it's working then. But the problem is we have lots of tests already written but this experimental ESM support is a braking change so it will be really hard to switch to that.

**Comment by borisdiakur** [comment]
Hi @Zorkann 👋

Here is what I got so far regarding the first case:

In [liquid version 4.6](https://github.com/emdgroup-liquid/liquid/releases/tag/v4.6.0) all Web Components are automatically registered with the Custom Elements Registry ([diff](https://github.com/emdgroup-liquid/liquid/commit/e618d96bb6e74a22e21479e379cc293bedfc0f3e#diff-a0b18f961e23905f7a524b79e85e27357268a11d6addc09d1368339be7fde85aR15), [Stencil Docs](https://stenciljs.com/docs/react#includedefinecustomelements)). This seems to trigger a race condition in the test, since both tests run in parallel: It looks like the button component has already added event listeners, but the necessary refs used in the event handlers have not been set up yet, as the component has not hydrated yet.
__TLDR__: [You need to wait for the component to hydrate](https://emdgroup-liquid.github.io/liquid/guides/testing/). Here is what you can do:

```tsx
import React from 'react'
import { render, screen, waitFor, fireEvent } from '@testing-library/react'
import App from './App'

test('renders heading', async () => {
  render(<App />)
  const heading = screen.getByText('zxcM')
  expect(heading).toBeInTheDocument()
  await waitFor(() => expect(heading).toHaveClass('hydrated')) // <-- you need this line
  fireEvent.click(heading)
})

test('renders headingW', async () => {
  render(<App />)
  const heading = screen.getByText('zxcM')
  expect(heading).toBeInTheDocument()
  await waitFor(() => expect(heading).toHaveClass('hydrated')) // <-- you need this line
  fireEvent.click(heading)
})
```

I'll need to investigate further if there is something I need to fix in the `ld-button` component.

What I noticed as well is that you can use [`userEvent`](https://testing-library.com/docs/user-event/intro) instead of `fireEvent` without waiting for hydration. I'm not sure why this works, it may be just "luck", because the tests do not really test anything after the click, so I wouldn't recommend it as a workaround for now. But here is the example for the sake of completeness:

```tsx
import React from 'react'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'

test('renders heading', async () => {
  render(<App />)
  const heading = screen.getByText('zxcM')
  expect(heading).toBeInTheDocument()
  userEvent.click(heading)
})

test('renders headingW', async () => {
  render(<App />)
  const heading = screen.getByText('zxcM')
  expect(heading).toBeInTheDocument()
  userEvent.click(heading)
})
```

For the second case with the `ld-modal` component it's pretty much the same thing: The component tries to remove an event listener, which should be attached to the host element, which is not there, because it has not yet been rendered. Here you can also wait for the component to hydrate to get rid of the error message:

```tsx
import React from 'react'
import { render, waitFor } from '@testing-library/react'
import App from './App'

async function waitForLiquidToHydrate() {
  return waitFor(() => {
    // eslint-disable-next-line testing-library/no-node-access
    Array.from(document.querySelectorAll('*'))
      .filter((e) => e.tagName.startsWith('LD-'))
      .forEach((component) => {
        expect(component).toHaveClass('hydrated')
      })
  })
}

test('renders heading', async () => {
  render(<App />)
  await waitForLiquidToHydrate()
})
```

I will check if I can include guards in liquid, so that such things don't happen again.
